### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by leosimony** [EoleDev/aker-ui-client#8]
Hello, Hope you are doing good :-)

Are you looking to or any idea on improving this aker UI. I am looking for an option like, add user button creates a user in the aker server?

**Comment by EoleDev** [comment]
Hi @leosimony,

In the source code, I saw the columns title error.
I will fix it right now.

**Comment by EoleDev** [comment]
Hi @leosimony,

I built the UI and updated it in the main project [aker-ui](https://github.com/EoleDev/aker-ui)
You may update your local version.
